kind: Service
apiVersion: v1
metadata:
  name: iemdb-front-service
  labels:
    app: iemdb-front-service
spec:
  type: NodePort
  selector:
    app: iemdb-frontend
  ports:
    - port: 80
      nodePort: 31098
      targetPort: 80
